POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InV3YWFnYmFpMUBnbWFpbC5jb20iLCJleHAiOjE3MjkzODgxNTgsInVzZXJJZCI6Mn0.OzleZ2vjRN4xsmhhmMPQ0XnPLLNOXHtj_X7rxsBjGF8

{
  "name": "real event 2.2",
  "description": "This is an real event 2.2",
  "location": "real location 2.2",
  "dateTime": "2024-01-09T15:30:00.000Z"
}